import Ionicons from "@expo/vector-icons/Ionicons";

const ICON_MAP: Record<string, keyof typeof Ionicons.glyphMap> = {
  wallet: "wallet-outline",
  "piggy-bank": "wallet-outline",
  banknote: "cash-outline",
  coins: "cash-outline",
  "hand-coins": "cash-outline",
  "dollar-sign": "cash-outline",
  "credit-card": "card-outline",
  receipt: "receipt-outline",
  landmark: "business-outline",
  "trending-up": "trending-up-outline",
  "trending-down": "trending-down-outline",
  percent: "pricetag-outline",
  briefcase: "briefcase-outline",
  "building-2": "business-outline",
  store: "storefront-outline",
  "shopping-bag": "bag-handle-outline",
  "shopping-cart": "cart-outline",
  package: "cube-outline",
  home: "home-outline",
  hotel: "bed-outline",
  utensils: "restaurant-outline",
  coffee: "cafe-outline",
  wine: "wine-outline",
  beer: "beer-outline",
  car: "car-outline",
  bike: "bicycle-outline",
  bus: "bus-outline",
  train: "train-outline",
  fuel: "flash-outline",
  plane: "airplane-outline",
  truck: "bus-outline",
  "map-pin": "location-outline",
  globe: "globe-outline",
  heart: "heart-outline",
  "heart-pulse": "pulse-outline",
  stethoscope: "medkit-outline",
  pill: "medkit-outline",
  dumbbell: "barbell-outline",
  activity: "pulse-outline",
  baby: "happy-outline",
  "graduation-cap": "school-outline",
  book: "book-outline",
  sparkles: "sparkles-outline",
  film: "film-outline",
  tv: "tv-outline",
  music: "musical-notes-outline",
  "gamepad-2": "game-controller-outline",
  ticket: "ticket-outline",
  gift: "gift-outline",
  shirt: "shirt-outline",
  scissors: "cut-outline",
  "paw-print": "paw-outline",
  dog: "paw-outline",
  smartphone: "phone-portrait-outline",
  wifi: "wifi-outline",
  zap: "flash-outline",
  cpu: "hardware-chip-outline",
  wrench: "build-outline",
  hammer: "hammer-outline",
  "clipboard-list": "clipboard-outline",
  calendar: "calendar-outline",
  clock: "time-outline",
  bell: "notifications-outline",
  umbrella: "umbrella-outline",
  "flower-2": "flower-outline",
  mountain: "image-outline",
  waves: "water-outline",
  "cloud-rain": "rainy-outline",
  "bar-chart-2": "stats-chart-outline",
  award: "trophy-outline",
  tag: "pricetag-outline",
};

export function TypeIcon({
  name,
  color,
  size = 16,
}: {
  name?: string | null;
  color: string;
  size?: number;
}) {
  const icon = (name && ICON_MAP[name]) || "cash-outline";
  return <Ionicons name={icon} size={size} color={color} />;
}
